# mytheme <- theme_minimal() + theme(axis.ticks = element_line(linewidth = 0.2, color = "black"), 
#                                  axis.text = element_text(size = 5, color="black",family = "Helvetica"),
#                                  axis.title = element_text(size=7, vjust = -0.5, color = "black",family = "Helvetica"),
#                                  legend.text = element_text(size=5 family = "Helvetica"), 
#                                  legend.title = element_text(size = 6, face = "bold",family = "Helvetica"),
#                                  legend.margin = margin(r = 10, l = 5, t = 5, b = 2),
#                                  legend.key.size = unit(15, "pt"),
#                                  panel.border = element_rect(linewidth = 0.4, fill = FALSE), 
#                                  panel.background = element_blank(),   
#                                  panel.grid = element_line(linewidth =0.2),
#                                  plot.title = element_text(family = "Helvetica"),
#                                  plot.margin = margin(t = 10, r = 10, b = 10, l = 10),
#                                  strip.text = element_text(size=7, face="bold",family = "Helvetica"),   
#                                  strip.background = element_blank(),
#                                  text = element_text(family = "Helvetica", base_size=5))            # General text
mytheme <- theme_minimal() + theme(axis.text = element_text(color = "black"),
                                 axis.ticks = element_line(linewidth = 0.2), 
                                 axis.title = element_text(size=7, vjust = -0.5),
                                 legend.title = element_text(size = 7, face = "bold"),
                                 legend.margin = margin(r = 10, l = 5, t = 5, b = 2),
                                 legend.key.size = unit(15, "pt"),
                                 panel.border = element_rect(linewidth = 0.4, fill = FALSE), 
                                 panel.background = element_blank(),   
                                 panel.grid = element_line(linewidth =0.2),
                                 plot.margin = margin(t = 10, r = 10, b = 10, l = 10),
                                 strip.text = element_text(size=7, face="bold"),   
                                 strip.background = element_blank(),
                                 text = element_text(family = "Helvetica",color="black", size=7))            # General text